# Generated by Django 4.2.7 on 2024-06-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_auto_20201222_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio_total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
